/**
 * Build script for creating separate core and admin entry points.
 *
 * This script generates filtered component exports for:
 * - Core build: All components except admin-only ones (le-component, le-slot)
 * - Admin build: All components
 *
 * Run: node scripts/build-targets.mjs
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

// Components that are admin-only and should be excluded from core build
const ADMIN_ONLY_COMPONENTS = ['le-component', 'le-slot'];

/**
 * Get all component directories from src/components
 */
function getComponentDirs() {
  const componentsDir = path.join(rootDir, 'src', 'components');
  return fs
    .readdirSync(componentsDir, { withFileTypes: true })
    .filter(dirent => dirent.isDirectory())
    .map(dirent => dirent.name);
}

/**
 * Convert component directory name to PascalCase class name
 * e.g., 'le-card' -> 'LeCard'
 */
function toPascalCase(name) {
  return name
    .split('-')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

/**
 * Generate the entry file content (without defineCustomElements)
 */
function generateEntryContent(components, includeAdminComponents) {
  const filteredComponents = includeAdminComponents ? components : components.filter(name => !ADMIN_ONLY_COMPONENTS.includes(name));

  const imports = filteredComponents
    .map(name => {
      const className = toPascalCase(name);
      return `export { ${className} } from './components/${name}/${name}';`;
    })
    .join('\n');

  return `/**
 * ${includeAdminComponents ? 'Full' : 'Core'} Le-Kit component exports
 * ${includeAdminComponents ? 'Includes all components with admin mode support' : 'Excludes admin-only components (le-component, le-slot)'}
 * 
 * Auto-generated by scripts/build-targets.mjs
 * Do not edit manually.
 */

// Component class exports
${imports}

// Re-export utilities and types from main index
export { generateId, parseCommaSeparated, slotHasContent } from './utils/utils';
export { getMode, setGlobalMode, getTheme, setGlobalTheme } from './global/app';
export type { LeKitMode, LeKitTheme } from './global/app';
export { leAlert, leConfirm, lePrompt } from './components/le-popup/le-popup.api';
export type { PopupOptions } from './components/le-popup/le-popup.api';
export type { PopupResult, PopupType, PopupPosition } from './components/le-popup/le-popup';

// Type exports
export type * from './types/options';
export type * from './types/blocks';
`;
}

/**
 * Main build function
 */
function buildEntryPoints() {
  const components = getComponentDirs();

  console.log('📦 Generating component entry points...');
  console.log(`   Found ${components.length} components`);
  console.log(`   Admin-only: ${ADMIN_ONLY_COMPONENTS.join(', ')}`);

  // Generate core entry (excludes admin components)
  const coreContent = generateEntryContent(components, false);
  const corePath = path.join(rootDir, 'src', 'index-core.ts');
  fs.writeFileSync(corePath, coreContent);
  console.log(`   ✅ Generated src/index-core.ts (${components.length - ADMIN_ONLY_COMPONENTS.length} components)`);

  // Generate admin entry (includes all components)
  const adminContent = generateEntryContent(components, true);
  const adminPath = path.join(rootDir, 'src', 'index-admin.ts');
  fs.writeFileSync(adminPath, adminContent);
  console.log(`   ✅ Generated src/index-admin.ts (${components.length} components)`);

  console.log('✨ Entry points generated successfully!');
}

// Run the build
buildEntryPoints();
